// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannel(arg1, arg2) {
  return window['go']['app']['App']['AddChannel'](arg1, arg2);
}

export function AddLog(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddLog'](arg1, arg2, arg3);
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function GetChannels() {
  return window['go']['app']['App']['GetChannels']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConnectedClients() {
  return window['go']['app']['App']['GetConnectedClients']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetVideoFiles(arg1) {
  return window['go']['app']['App']['GetVideoFiles'](arg1);
}

export function PlayTestPattern(arg1) {
  return window['go']['app']['App']['PlayTestPattern'](arg1);
}

export function PlayVideoOnChannel(arg1, arg2) {
  return window['go']['app']['App']['PlayVideoOnChannel'](arg1, arg2);
}

export function RemoveChannel(arg1) {
  return window['go']['app']['App']['RemoveChannel'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectTestPatternPath() {
  return window['go']['app']['App']['SelectTestPatternPath']();
}

export function SelectVideoPath() {
  return window['go']['app']['App']['SelectVideoPath']();
}

export function StartChannel(arg1) {
  return window['go']['app']['App']['StartChannel'](arg1);
}

export function StopChannel(arg1) {
  return window['go']['app']['App']['StopChannel'](arg1);
}

export function ToggleChannel(arg1) {
  return window['go']['app']['App']['ToggleChannel'](arg1);
}

export function UpdateChannel(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateChannel'](arg1, arg2, arg3);
}

export function UpdateConfig(arg1) {
  return window['go']['app']['App']['UpdateConfig'](arg1);
}
