// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {channel} from '../models';
import {config} from '../models';
import {websocket} from '../models';
import {app} from '../models';

export function AddChannel(arg1:string,arg2:string):Promise<channel.Channel>;

export function AddLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function GetChannels():Promise<Array<channel.Channel>>;

export function GetConfig():Promise<config.Config>;

export function GetConnectedClients():Promise<Array<websocket.ClientInfo>>;

export function GetLogs():Promise<Array<app.LogEntry>>;

export function GetVideoFiles(arg1:string):Promise<Array<string>>;

export function PlayTestPattern(arg1:string):Promise<void>;

export function PlayVideoOnChannel(arg1:string,arg2:string):Promise<void>;

export function RemoveChannel(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectTestPatternPath():Promise<string>;

export function SelectVideoPath():Promise<string>;

export function SetChannelSRTHost(arg1:string,arg2:string):Promise<void>;

export function StartChannel(arg1:string):Promise<void>;

export function StopAllStreams():Promise<void>;

export function StopChannel(arg1:string):Promise<void>;

export function ToggleChannel(arg1:string):Promise<void>;

export function UpdateChannel(arg1:string,arg2:string,arg3:string):Promise<channel.Channel>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
